/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.MesaData;
import entidades.Mesa;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Equipo
 */
public class VistaCrearMesa extends javax.swing.JInternalFrame {

    FondoPanel fondo = new FondoPanel();

    private MesaData mesa;

    public VistaCrearMesa() {
        this.setContentPane(fondo);
        initComponents();
        mesa = new MesaData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpVistaCrearMesa = new FondoPanel();
        jtCapacidad = new javax.swing.JTextField();
        jtNum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbGuardar = new javax.swing.JButton();

        setClosable(true);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Capacidad:");

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CREAR MESA");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Número:");

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpVistaCrearMesaLayout = new javax.swing.GroupLayout(jpVistaCrearMesa);
        jpVistaCrearMesa.setLayout(jpVistaCrearMesaLayout);
        jpVistaCrearMesaLayout.setHorizontalGroup(
            jpVistaCrearMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpVistaCrearMesaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpVistaCrearMesaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpVistaCrearMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpVistaCrearMesaLayout.createSequentialGroup()
                        .addGroup(jpVistaCrearMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jpVistaCrearMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtCapacidad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpVistaCrearMesaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(71, 71, 71))))
        );
        jpVistaCrearMesaLayout.setVerticalGroup(
            jpVistaCrearMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpVistaCrearMesaLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpVistaCrearMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(jpVistaCrearMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jpVistaCrearMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardar)
                    .addComponent(jbCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpVistaCrearMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpVistaCrearMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        int res = JOptionPane.showConfirmDialog(this, "¿Desea salir sin guardar los cambios?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        try {
            if (jtNum.getText().isEmpty() || jtCapacidad.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No puede haber campos vacíos");
            } else {
                int num = Integer.parseInt(jtNum.getText());
                int cap = Integer.parseInt(jtCapacidad.getText());
                int res = JOptionPane.showConfirmDialog(this, "¿Está seguro de crear una nueva mesa? ", "Confirmacion", JOptionPane.YES_NO_OPTION);
                if (res == JOptionPane.YES_OPTION) {
                    Mesa mNueva = new Mesa(num, true, true, cap);
                    System.out.println("Número de mesa: " + num);
                    System.out.println("Capacidad: " + cap);
                    mesa.nuevaMesa(mNueva);
                    jtNum.setText("");
                    jtCapacidad.setText("");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error. Los campos ´Número´y ´Capacidad´ sólo aceptan dígitos. | " + e, "Formato erróneo.", JOptionPane.ERROR_MESSAGE);
        }

//                (jtNum.getText().isEmpty() || jtNum.getText().equals("Asigne un número de mesa")) {
//                if (jtCapacidad.getText().isEmpty() || jtCapacidad.getText().equals("Especifique la capacidad de la mesa")) {
//                JOptionPane.showMessageDialog(this, "No puede haber campos vacíos");
//            }} else {
//            int num = Integer.parseInt(jtNum.getText());
//            int cap = Integer.parseInt(jtCapacidad.getText());
//
//            if (jrbEstado.isSelected()) {
//                boolean a;
//            }
//            if (jrbLibre.isSelected()) {
//                boolean b;
//            }
//            int res = JOptionPane.showConfirmDialog (this, "¿Está seguro de crear una nueva mesa? ", "Confirmacion", JOptionPane.YES_NO_OPTION);
//            if(res ==JOptionPane.YES_OPTION){
//            Mesa mNueva = new Mesa (num, a, b, cap);
//            mesa.nuevaMesa(mNueva);
//            jtNum.setText("");
//            jtCapacidad.setText("");
//            }
//        }} catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Error. Los campos ´Número´y ´Capacidad´ sólo aceptan dígitos. | " + e, "Formato erróneo.", JOptionPane.ERROR_MESSAGE);
//        }
    }//GEN-LAST:event_jbGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JPanel jpVistaCrearMesa;
    private javax.swing.JTextField jtCapacidad;
    private javax.swing.JTextField jtNum;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/Fondo2.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

}
